services:
  altschool_de:
    image: postgres:13
    environment:
      - POSTGRES_USER=****
      - POSTGRES_PASSWORD=****
      - POSTGRES_DB=***
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - airflow
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=***@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=***
#    ports:
#      - "8080:80"
#    volumes:
#      - ./data_pgadmin:/var/lib/pgadmin
networks:
  airflow:
    external:
      name: airflow_default




